name: Python CI

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu to run your tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code to the runner

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the version of Python you want to use

    - name: Install virtualenv
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv  # Install virtualenv

    - name: Create virtual environment
      run: |
        python -m virtualenv venv  # Create a virtual environment named 'venv'
        source venv/bin/activate  # Activate the virtual environment

    - name: Install dependencies
      run: |
        source venv/bin/activate  # Activate the virtual environment
        pip install -r requirements.txt  # Install the required dependencies

    - name: Set up environment variables
      run: |
        echo "MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }}" >> $GITHUB_ENV
        echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> $GITHUB_ENV
        # Set MongoDB credentials as environment variables

    - name: Run tests
      run: |
        source venv/bin/activate  # Ensure virtualenv is activated
        python -m unittest discover tests/  # Run all tests in the tests/ directory

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-report.xml  # Optional: you can upload test results (if you generate them)
